<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productRecords = ([
    [
        'category_id' => 1,
        'brand_id' => 1,
        'name' => 'Camiseta Básica Blanca',
        'code' => 'TSHIRT001',
        'color' => 'Blanco',
        'family_color' => 'Blanco',
        'group_code' => 'TSHIRT',
        'price' => 19.99,
        'discount' => 2.00,
        'discount_type' => 'fixed',
        'final_price' => 17.99,
        'video' => null,
        'image' => 'tshirt001.jpg',
        'description' => 'Camiseta básica de algodón, ideal para uso diario.',
        'wash_care' => 'Lavar a máquina en frío',
        'keywords' => 'camiseta, blanca, básica, algodón',
        'fabric' => 'Algodón',
        'pattern' => 'Liso',
        'sleeve' => 'Corta',
        'fit' => 'Regular',
        'occasion' => 'Casual',
        'size' => 'M',
        'weight' => 0.2,
        'stock' => 50,
        'meta_title' => 'Camiseta Básica Blanca',
        'meta_description' => 'Camiseta básica blanca de algodón para hombre.',
        'meta_keywords' => 'camiseta, blanca, algodón',
        'status' => 1,
        'is_featured' => 'Yes',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => 2,
        'brand_id' => 2,
        'name' => 'Pantalón Jeans Azul',
        'code' => 'JEANS001',
        'color' => 'Azul',
        'family_color' => 'Azul',
        'group_code' => 'JEANS',
        'price' => 39.99,
        'discount' => 5.00,
        'discount_type' => 'fixed',
        'final_price' => 34.99,
        'video' => null,
        'image' => 'jeans001.jpg',
        'description' => 'Jeans azul clásico, corte recto.',
        'wash_care' => 'Lavar a máquina con colores similares',
        'keywords' => 'jeans, pantalón, azul, clásico',
        'fabric' => 'Denim',
        'pattern' => 'Liso',
        'sleeve' => null,
        'fit' => 'Slim',
        'occasion' => 'Casual',
        'size' => '32',
        'weight' => 0.5,
        'stock' => 30,
        'meta_title' => 'Pantalón Jeans Azul',
        'meta_description' => 'Jeans azul clásico para hombre.',
        'meta_keywords' => 'jeans, azul, pantalón',
        'status' => 1,
        'is_featured' => 'No',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => 3,
        'brand_id' => 1,
        'name' => 'Vestido Floral',
        'code' => 'DRESS001',
        'color' => 'Rojo',
        'family_color' => 'Rojo',
        'group_code' => 'DRESS',
        'price' => 49.99,
        'discount' => 10.00,
        'discount_type' => 'fixed',
        'final_price' => 39.99,
        'video' => null,
        'image' => 'dress001.jpg',
        'description' => 'Vestido floral para ocasiones especiales.',
        'wash_care' => 'Lavar a mano',
        'keywords' => 'vestido, floral, mujer, elegante',
        'fabric' => 'Poliéster',
        'pattern' => 'Floral',
        'sleeve' => 'Sin mangas',
        'fit' => 'Ajustado',
        'occasion' => 'Fiesta',
        'size' => 'S',
        'weight' => 0.3,
        'stock' => 20,
        'meta_title' => 'Vestido Floral',
        'meta_description' => 'Vestido floral elegante para mujer.',
        'meta_keywords' => 'vestido, floral, mujer',
        'status' => 1,
        'is_featured' => 'Yes',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => 4,
        'brand_id' => 3,
        'name' => 'Camisa Formal Celeste',
        'code' => 'SHIRT001',
        'color' => 'Celeste',
        'family_color' => 'Azul',
        'group_code' => 'SHIRT',
        'price' => 29.99,
        'discount' => 0,
        'discount_type' => null,
        'final_price' => 29.99,
        'video' => null,
        'image' => 'shirt001.jpg',
        'description' => 'Camisa formal celeste para oficina.',
        'wash_care' => 'Lavar en seco',
        'keywords' => 'camisa, formal, celeste, oficina',
        'fabric' => 'Algodón',
        'pattern' => 'Liso',
        'sleeve' => 'Larga',
        'fit' => 'Slim',
        'occasion' => 'Formal',
        'size' => 'L',
        'weight' => 0.25,
        'stock' => 40,
        'meta_title' => 'Camisa Formal Celeste',
        'meta_description' => 'Camisa formal celeste para hombre.',
        'meta_keywords' => 'camisa, formal, celeste',
        'status' => 1,
        'is_featured' => 'No',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => 5,
        'brand_id' => 2,
        'name' => 'Zapatillas Running',
        'code' => 'SHOES001',
        'color' => 'Negro',
        'family_color' => 'Negro',
        'group_code' => 'SHOES',
        'price' => 59.99,
        'discount' => 5.00,
        'discount_type' => 'fixed',
        'final_price' => 54.99,
        'video' => null,
        'image' => 'shoes001.jpg',
        'description' => 'Zapatillas deportivas para correr.',
        'wash_care' => 'Limpiar con paño húmedo',
        'keywords' => 'zapatillas, running, deporte',
        'fabric' => 'Sintético',
        'pattern' => 'Liso',
        'sleeve' => null,
        'fit' => null,
        'occasion' => 'Deporte',
        'size' => '42',
        'weight' => 0.7,
        'stock' => 25,
        'meta_title' => 'Zapatillas Running',
        'meta_description' => 'Zapatillas deportivas para correr.',
        'meta_keywords' => 'zapatillas, running, deporte',
        'status' => 1,
        'is_featured' => 'Yes',
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'category_id' => 6,
        'brand_id' => 1,
        'name' => 'Campera de Cuero',
        'code' => 'JACKET001',
        'color' => 'Negro',
        'family_color' => 'Negro',
        'group_code' => 'JACKET',
        'price' => 99.99,
        'discount' => 20.00,
        'discount_type' => 'fixed',
        'final_price' => 79.99,
        'video' => null,
        'image' => 'jacket001.jpg',
        'description' => 'Campera de cuero genuino, estilo clásico.',
        'wash_care' => 'Limpieza en seco',
        'keywords' => 'campera, cuero, hombre',
        'fabric' => 'Cuero',
        'pattern' => 'Liso',
        'sleeve' => 'Larga',
        'fit' => 'Regular',
        'occasion' => 'Casual',
        'size' => 'M',
        'weight' => 1.2,
        'stock' => 10,
        'meta_title' => 'Campera de Cuero',
        'meta_description' => 'Campera de cuero genuino para hombre.',
        'meta_keywords' => 'campera, cuero, hombre',
        'status' => 1,
        'is_featured' => 'No',
        'created_at' => now(),
        'updated_at' => now(),
    ],
]);

    Product::insert($productRecords);
    }


}
